### ISSUE TITLE
Error on deploy

### ISSUE THREAD

**Issue by PMLS3** [wobsoriano/nuxt-proxy#6]
I am using Google Cloud run when deploying my site. The plugin works 100 in development but getting the following build error.

TypeError: debug_1.Debug.extend is not a function
    at Object.<anonymous> (/usr/src/app/.output/server/node_modules/http-proxy-middleware/dist/plugins/default/debug-proxy-errors-plugin.js:5:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/.output/server/node_modules/http-proxy-middleware/dist/plugins/default/index.js:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

In my docker file I expose port 8080, not sure if the could be the reason?
ERROR: (gcloud.run.services.update) Cloud Run error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

**Comment by wobsoriano** [comment]
Can you try the latest version and reopen it if the issue still persists? Thanks!

**Comment by DamianGlowala** [comment]
@wobsoriano, what have you changed to remove this issue? I am currently facing it with the latest Nuxt edge and I can't find any workaround :/

**Comment by DamianGlowala** [comment]
Manually changing the highlighted import to `'debug'` in the production bundle solves the problem. No idea why this happens though.

![image](https://user-images.githubusercontent.com/48835293/215069166-37cff8fb-41c4-4839-9d87-5e565eeb6a88.png)

**Comment by joseehilton147** [comment]
issue persist

![image](https://user-images.githubusercontent.com/53986027/227043285-1ebd168f-5253-4615-9a8b-4a1c1063e8b3.png)

**Comment by being8000** [comment]
same issue

**Comment by JensvdHeydt** [comment]
Same here. Don't understand why I run into this error now since it seams to exist since 2023. Can this be addressed?

**Comment by DamianGlowala** [comment]
Why don't you switch to https://www.jsdocs.io/package/h3#proxyRequest? Are there any blockers?

**Comment by JensvdHeydt** [comment]
@DamianGlowala, thanks for the recommendation. I didn't want to switch lib since I'm using this package in a nuxt project. But I guess I have to....
